name: 'dpm'
description: 'Development Performance metrics'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
    default: $
  datadog-api-token:
    description: 'DataDog Token'
    required: true
    default: $
  metrics-prefix:
    description: 'Metrics prefix'
    required: false
    default: 'dpm'
  teams:
    description: 'Team tags, check README.md for examples.'
    required: false
    default: '[]'
  custom-tags: 
    description: 'Custom tags e.g ["product:gbp", "division:flutter"]'
    required: false
    default: '[]'
runs:
  using: 'node12'
  main: 'dist/index.js'