name: 'dpm'
description: 'Development Performance metrics'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
    default: $
  datadog-api-token:
    description: 'DataDog Token'
    required: true
    default: $
  datadog-api-host:
    description: 'DataDog API Host'
    required: false
    default: 'app.datadoghq.com'
  metrics-prefix:
    description: 'Metrics prefix'
    required: false
    default: 'dpm'
  teams:
    description: 'Team tags, check README.md for examples.'
    required: false
    default: '[]'
  custom-tags: 
    description: 'Custom tags e.g ["product:gbp", "division:flutter"]'
    required: false
    default: '[]'
  labels-whitelist:
    description: 'Labels whitelisted to be used as tags'
    required: false
    default: '[]'
  branches-whitelist:
    description: 'Branches whitelisted to be used as tags'
    required: false
    default: '[]'
runs:
  using: 'node16'
  main: 'dist/index.js'