name: Development Performance Metrics
on:
  pull_request:
    types: [opened, closed]
jobs:
  metrics:
    if: |
      (github.event.action == 'closed' &&
      github.event.pull_request.merged == true) ||
      github.event.action == 'opened'
    name: Track merge request activity
    runs-on: ubuntu-latest
    steps:
      - id: datadog-metrics
        uses: caquino/dpm@v1.0.0
        with:
          datadog-metric-prefix: 'github.action'
          teams: '[ "dpm", "development", "devops" ]'
          datadog-api-token: ${{ secrets.DD_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          custom-tags: '["product:dpm", "environment:test"]'